language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "592115001" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t 592115001/se234-lab10-backend  .
- docker push 592115001/se234-lab10-backend
- docker pull 592115001/se234-lab10-client
script:
- docker-compose -H "tcp://54.213.117.250:1234" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: pTX1MPLASKlJsKU6m6T1hYruF2RlNT2Q1E89nQo8ZHmGKHIWrUdczvMPzCd++QzSR5VhsvSTHMWiipAOOJwfIDJ5P0ft0eZUqU4/9KOyu04CLMAxnot3RtWNlCrDNXpZcbcoQDdkNGl6bo13DyeWYMftUQ7Q+3cFDsT13L43If9F3YlDe0gAvpPyvROAhif1YKXX9NHUlYXry9QWvnuphIGQtW9KAU3xrtmyNc3ax+tHre+s1Y4J4D7qAuf0FcdHJokeLnX31rSsDFyd0MBEOYF3I2r6quDhXDDjm0K96aViSRN97+2s686gsG6hMc/+fhE+XkdvwTMVhJhYIkXM+Afao6XQXuspwL/mFUBBS3zdcaqiGzoH9DPw+1xoVXxfiaO92+zCKCPiGO3LhvaWC0lZEabBMRihCy+ci2o+X8KshJDyI5aUmL4deuSUAhlLdeOM2UbjI5+oNB6ktK+gTsOtbRAeSs/yOCAGQvKx9QmXv0nCZy91CNRCcLtKJ4uy4X9OgGhIPVeIKqxygvJ+gZlxLG9mQ/FhDe3lRhLSo++oIbo1C/Nj06Z5rT7ubleMJ92HXWobQIkm+9OBd2/NElzrC8tx7VqcIytY4wMDgAz9VpYMHwCRlhR1Q9s9nqweBBpjWE/19lXPmao3QjgAFkPpcxBtfS5FSKRmuNX8LZE=
  - secure: CpRVdpk8JNwBgMAp2Mz+MRKK5ubW1QkbTBD09KTr/eWUWvAXKRfWrruNf0m+xZsUKqO09H4r01xybPQ2Ike+YtVGm5FZIPktaFJnSzmLwM7gCZspRuqnoqY4fu+72xZfeWuAYxNLjPLxZCwez7p/VeNT9WAigd3db51srN5aMj1Bd/mwqzaNNboYswmmVp9cOLQYYBcX4Z7G7cn+aQGbahci+b2j0GPmhGaCCmzcNoTl91phdqsgBghvG0tpLDtD9x7WI1x3WyyIKMN1buCY+rSY0tynrMNnytzRkQZa9vpe8kYmQ+Oyn4CQ6H9K21OHqBtHF4qdeGbxi/2gz13Ip7jJOYicUtGotNvD0MhoFb/8r2m50FMnvdTLh0o+QOBYMcrqGywDNx/JvuFemBhJYAqGvRFFPtrhEpNhI+uujmT1DimHsxeXuVXahF48aCaBocrnt7tSQRN7MHWJrIuIwjfABa3pnAFqbuIskdP8h7bwIylp/wnYgtAffm/70iSdIqQMMzPVJ+WPI+NwEX7P8AqXkHrh3hoZpTptg/rFDR2/reKQMIFBEur7YiEzPPDlk72Nr0d5PGhtdY4kq4EKsrDw7t35apBDpOuDzCbWplYd1V2xcqMkB+3EG3tXli3XLXYK+ba8WsdC/wPUFKuHMroWNmpPl9uM7H8e/Ts5RRI=
  - secure: oFIpUEg6C6C/6x4O+7TIzG8DTcX/T7/ZV2/CF8PSm9hLjBuzQ/V3OJaXXxUNIiwS6mTaU1Y7o2dc0wjKkhQzCMg1vf1s4eBnC2aZD9a3oGDz+HBSDsy0IRddyNWdmTaxvwBQ26gWYzOOyZwduiu2PZKE2SSu1aUwAQZPGN45qGCgehB3hXQUXdZ6A3KNYcB06iXvtPufgrOmbpNgBXShkjUsrw5pEqeJM7b8W25umzlfwtY1G7t/Zx5Y/7Jc2TvvNQgfXRHNMos6wnulbUvThOexfOWx5qZYM4jtJGADf5+/HRVvorhZj1ed8dElhV1OUC/OTslbC7Qxqy+tgFKyxZT4XggJKraCKKdbCG1YCecYWRrjcKVPm3li3IR92leqvFEFUNh3YrRB/OfadspD3sVGo+/1xq6iDmy2POd9pDfL3ohvgk3wsIeGomP2W1FJIU1ELhVsPu0lzIkzxoIR/mrKEtLDgilnPTiBXswTcLS91HtcrtGR9X2dFQR+GI/RwM5lB6Hb9crwQz3hKtDpD3xeJf8s134zjG9+OubLeK7d2kqXQAJPGmz7hqUgG0ZK6MqJO7XIqp60XXuKAW/+bEAc6XcZENM3QZAefzUqDBvjeqL6iYRtK3xhsemhC70bpWpXOVUVrnsY4CGJ1tBdTGcvMmpPnKQm0voHX9QhKx8=
